#!/usr/bin/env node
// Parse every Ghostty theme file in /themes and emit lib/themes.generated.ts,
// a typed module consumed by the React app. Runs automatically before
// `next dev` and `next build` via npm `predev`/`prebuild`.

import { readFile, readdir, writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const THEMES_DIR = join(ROOT, "themes");
const OUT_DIR = join(ROOT, "lib");
const OUT_FILE = join(OUT_DIR, "themes.generated.ts");

const FEATURED = [
  "Muxy",
  "Muxy Light",
  "Dracula",
  "TokyoNight",
  "TokyoNight Day",
  "Catppuccin Mocha",
  "GitHub Dark",
  "GitHub Light Default",
  "Nord",
  "Gruvbox Dark",
  "Monokai Pro",
  "Atom One Dark",
  "Ayu",
  "Ayu Mirage",
  "Rose Pine",
  "Rose Pine Dawn",
  "Everforest Dark Hard",
  "Solarized Dark Patched",
  "iTerm2 Solarized Light",
];

function normalizeHex(raw) {
  if (!raw) return null;
  let s = String(raw).trim().toLowerCase();
  const rgbMatch = s.match(/^rgb:([0-9a-f]{2,4})\/([0-9a-f]{2,4})\/([0-9a-f]{2,4})$/i);
  if (rgbMatch) {
    const take2 = (c) => (c.length === 2 ? c : c.slice(0, 2));
    return `#${take2(rgbMatch[1])}${take2(rgbMatch[2])}${take2(rgbMatch[3])}`;
  }
  if (s.startsWith("#")) s = s.slice(1);
  if (/^[0-9a-f]{3}$/.test(s)) {
    return `#${s[0]}${s[0]}${s[1]}${s[1]}${s[2]}${s[2]}`;
  }
  if (/^[0-9a-f]{6}$/.test(s)) return `#${s}`;
  if (/^[0-9a-f]{8}$/.test(s)) return `#${s.slice(0, 6)}`;
  return null;
}

function parseTheme(text) {
  const palette = new Array(16).fill(null);
  let background = null;
  let foreground = null;
  let cursor = null;
  let selectionBg = null;
  let selectionFg = null;

  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim().toLowerCase();
    const value = line.slice(eq + 1).trim();
    if (key === "palette") {
      const subEq = value.indexOf("=");
      if (subEq === -1) continue;
      const idx = parseInt(value.slice(0, subEq).trim(), 10);
      if (!Number.isFinite(idx) || idx < 0 || idx > 15) continue;
      const hex = normalizeHex(value.slice(subEq + 1));
      if (hex) palette[idx] = hex;
    } else if (key === "background") {
      background = normalizeHex(value) ?? background;
    } else if (key === "foreground") {
      foreground = normalizeHex(value) ?? foreground;
    } else if (key === "cursor-color") {
      cursor = normalizeHex(value) ?? cursor;
    } else if (key === "selection-background") {
      selectionBg = normalizeHex(value) ?? selectionBg;
    } else if (key === "selection-foreground") {
      selectionFg = normalizeHex(value) ?? selectionFg;
    }
  }

  if (!background || !foreground) return null;
  for (let i = 0; i < 16; i++) {
    if (!palette[i]) palette[i] = foreground;
  }
  return {
    palette,
    background,
    foreground,
    cursor: cursor ?? foreground,
    selectionBg: selectionBg ?? foreground,
    selectionFg: selectionFg ?? background,
  };
}

async function main() {
  const entries = await readdir(THEMES_DIR, { withFileTypes: true });
  const themes = [];
  let skipped = 0;
  for (const ent of entries) {
    if (!ent.isFile() || ent.name.startsWith(".")) continue;
    const text = await readFile(join(THEMES_DIR, ent.name), "utf8");
    const parsed = parseTheme(text);
    if (!parsed) { skipped++; continue; }
    themes.push({ name: ent.name, ...parsed });
  }

  themes.sort((a, b) => a.name.localeCompare(b.name, "en", { sensitivity: "base" }));

  const order = new Map(FEATURED.map((n, i) => [n.toLowerCase(), i]));
  themes.sort((a, b) => {
    const ai = order.has(a.name.toLowerCase()) ? order.get(a.name.toLowerCase()) : Infinity;
    const bi = order.has(b.name.toLowerCase()) ? order.get(b.name.toLowerCase()) : Infinity;
    if (ai !== bi) return ai - bi;
    return a.name.localeCompare(b.name, "en", { sensitivity: "base" });
  });

  const featuredCount = themes.filter((t) => order.has(t.name.toLowerCase())).length;

  await mkdir(OUT_DIR, { recursive: true });

  const header = `// AUTO-GENERATED by scripts/build-themes.mjs — do not edit.
// ${themes.length} themes parsed from /themes (${skipped} skipped).
// Featured (first ${featuredCount}) are curated; the rest are alphabetical.
import type { Theme } from "./themes";

`;
  const body = `export const THEMES: Theme[] = ${JSON.stringify(themes, null, 2)};\n\nexport const FEATURED_COUNT = ${featuredCount};\n`;
  await writeFile(OUT_FILE, header + body);
  console.log(`Wrote ${themes.length} themes to lib/themes.generated.ts (skipped ${skipped}).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
